### PR TITLE
Start using GitHub Actions 

### PR DESCRIPTION
**Pull request by djjudas21**
Here's a summary of what's included in this PR:

* Enable a Pylint action
  - I have fixed a few of the existing lint errors (mostly style and formatting)
  - I'm no developer, so I have also disabled a number of checks in `.pylintrc` to get a clean lint pass. Ideally these disabled rules should be revisited in the future and fixed rather than disabled, but there's nothing too serious here. Mostly style rather than functionality.
* Enable a Pytest action
  - This just runs the existing tests from the module. They are currently failing and I don't know how to fix them. Needs someone who knows Python properly.
* Enable a Publish action
  - This publishes a module to PyPI when a Release is tagged in GitHub. You need to add a secret `PYPI_API_TOKEN` with your PyPI token to allow it to publish. But I guess don't worry about this until Pytest is running properly.
* Disable Travis and Appveyor

Really keen to get this module back into a state where it can be maintained :slightly_smiling_face:

### CODE REVIEW

**Comment by djjudas21** [comment]
Here's the clean pylint on my fork:
https://github.com/djjudas21/Piexif/actions/runs/4633293513

And here's the failing pytest on my fork:
https://github.com/djjudas21/Piexif/actions/runs/4633293511

**Comment by HerrMuellerluedenscheid** [comment]
Hi @djjudas21 whats the status of this MR? I think its a great and very valuable effort to move to github actions!

**Comment by davetapley** [comment]
Argh sorry @djjudas21 and @HerrMuellerluedenscheid I don't know how I missed this 🙈 

Thanks for the all the hard work. It's great work, so I'll merge now and make you a maintainer.

**Comment by davetapley** [comment]
@djjudas21 oh, apparently you already are a maintainer, so you should be able to push freely in future!

**Pull request merged**
